on:
  push:
    branches:
      - master

name: Release Packaging

jobs:
  release:
    name: Release Packaging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: dns-resolver
          path: target/release/dns-resolver
